---
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/ArgumentAlignment:
        Enabled: false # 10 app errors
      Layout/CommentIndentation:
        Enabled: false
      Layout/FirstArgumentIndentation:
        Enabled: false # 41 app errors
      Layout/FirstArrayElementIndentation:
        Enabled: false # 3 app errors
      Layout/FirstHashElementIndentation:
        Enabled: false # 5 app errors
      Layout/InitialIndentation:
        Enabled: false # 661 app errors
      Layout/TrailingEmptyLines:
        Enabled: false # 652 app errors
      Lint/UselessAssignment:
        Enabled: false # 1 app error
      Style/FrozenStringLiteralComment:
        Enabled: false # 666 app errors
