---
EnableDefaultLinters: true
linters:
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false # 661 app errors
      Layout/LineLength:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false # 652 app errors
      Layout/TrailingWhitespace:
        Enabled: false # 4 app errors
      Naming/FileName:
        Enabled: false
      Style/FrozenStringLiteralComment:
        Enabled: false # 666 app errors
      Lint/UselessAssignment:
        Enabled: false # 1 app error
      Rails/OutputSafety:
        Enabled: false
