inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Naming/MemoizedInstanceVariableName:
  Exclude:
    - "spec/**/*"

Rails/NotNullColumn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
