inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require:
  - ./lib/rubocop/cop/govuk/govuk_button_to.rb
  - ./lib/rubocop/cop/govuk/govuk_link_to.rb
  - ./lib/rubocop/cop/govuk/govuk_submit.rb

Govuk:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"
  Exclude:
    - "app/components/trainees/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Naming/MemoizedInstanceVariableName:
  Exclude:
    - "spec/**/*"

Rails/NotNullColumn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20210108163200_install_audited.rb"
