inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

Naming/MemoizedInstanceVariableName:
  Exclude:
    - "spec/**/*"

Rails/NotNullColumn:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Rails/CreateTableWithTimestamps:
  Exclude:
    - "db/migrate/20210108163200_install_audited.rb"
