require:
  - ../../lib/rubocop/cop/govuk/govuk_button_to.rb
  - ../../lib/rubocop/cop/govuk/govuk_link_to.rb
  - ../../lib/rubocop/cop/govuk/govuk_submit.rb

Govuk:
  Include:
    - "app/views/**/*"
    - "app/components/**/*"
  Exclude:
    - "app/components/trainees/confirmation/degrees/view.html.erb"
    - "app/components/personas/view.html.erb"

Govuk/GovukLinkTo:
  Exclude:
    - "app/components/govuk_button_link_to/view.rb"
