port: 5000

basic_auth_required: true
dttp:
  client_id: "application-registration-client-id-from-env"
  scope: "https://dttp-dev.crm4.dynamics.com/.default"
  client_secret: "client-secret-from-env"
  tenant_id: "tenant-id-from-env"
  api_base_url: "api-base-url-from-env"

# Used to add feature flags in the app to control access to certain features.
features:
  home_text: false
  use_ssl: true
