port: 5000
base_url: base_url required value

basic_auth_required: true
dttp:
  client_id: "application-registration-client-id-from-env"
  scope: "https://dttp-dev.crm4.dynamics.com/.default"
  client_secret: "client-secret-from-env"
  tenant_id: "tenant-id-from-env"
  api_base_url: "api-base-url-from-env"

# Used to add feature flags in the app to control access to certain features.
features:
  home_text: false
  use_ssl: true
  use_dfe_sign_in: true
  allow_user_creation: false

dfe_sign_in:
  identifier: identifier required value
  issuer: issuer required value
  profile: profile required value
  secret: secret required value
