update_trainees_to_dttp:
  cron: "0 0 * * *"
  class: "QueueTraineeUpdatesJob"
  queue: dttp
truncate_activerecord_session_store:
  cron: "0 0 * * *"
  class: "SessionStoreTruncateJob"
  queue: default
