# The url for the google doc feedback link (non-live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLSdYg4IA2tMiSfqIjM9CslVgFzsSazznD6VoT41g19sJYCwsLQ/viewform"

dttp:
  api_base_url: "https://dttp-dev.api.crm4.dynamics.com"

features:
  allow_user_creation: true
  use_dfe_sign_in: false
  basic_auth: false
