# The url for the google doc feedback link (non-live version)
feedback_link_url: "https://docs.google.com/forms/d/e/1FAIpQLSdYg4IA2tMiSfqIjM9CslVgFzsSazznD6VoT41g19sJYCwsLQ/viewform"

dttp:
  api_base_url: "https://dttp-dev.api.crm4.dynamics.com"

features:
  allow_user_creation: true
  use_dfe_sign_in: false
  basic_auth: false
  import_courses_from_ttapi: true
  routes_provider_led_postgrad: true
  routes_early_years_undergrad: true

pagination:
  records_per_page: 30

environment:
  name: development
