# The url for the google doc feedback link for recommended for award (non-live version)
recommended_for_award_feedback_url: "https://docs.google.com/forms/d/e/1FAIpQLSc5ZEOkwsd8NTh3USbaDIL2OSBUtzVFonm7whuXhzFmQK5DHw/viewform"

# The url for the google doc feedback link for submitting a trainee for trn (non-live version)
trn_submitted_feedback_url: "https://docs.google.com/forms/d/e/1FAIpQLSeewi8Fl9b90dXjyEX3tE72De8r9yxcFyl51vgOi7hE_fFp1g/viewform"

# The url for this app, also used by `dfe_sign_in`
base_url: https://qa.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp-test.crm4.dynamics.com/
  scope: https://dttp-test.crm4.dynamics.com/.default
  api_base_url: https://dttp-test.crm4.dynamics.com/api/data/v9.1

features:
  home_text: true
  use_dfe_sign_in: false
  routes:
    provider_led_postgrad: true
    early_years_undergrad: true
    school_direct_salaried: true
    school_direct_tuition_fee: true

pagination:
  records_per_page: 30
