# The url for this app, also used by `dfe_sign_in`
base_url: https://qa.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp-test.crm4.dynamics.com/
  scope: https://dttp-test.crm4.dynamics.com/.default
  api_base_url: https://dttp-test.crm4.dynamics.com/api/data/v9.1

features:
  home_text: true
  use_dfe_sign_in: false
