# The url for this app, also used by `dfe_sign_in`
base_url: https://staging.register-trainee-teachers.education.gov.uk

dttp:
  back_office_url: https://dttp-ppad.crm4.dynamics.com/
  scope: https://dttp-ppad.crm4.dynamics.com/.default
  api_base_url: https://dttp-ppad.crm4.dynamics.com/api/data/v9.1

dfe_sign_in:
  # URL that the users are redirected to for signing in
  issuer: https://pp-oidc.signin.education.gov.uk
  # URL of the users profile
  profile: https://pp-profile.signin.education.gov.uk
