dttp:
  api_base_url: "https://test-api-base-uri.com"
slack:
  default_channel: "test-channel"
  webhook_url: "https://test-slack-webhook-url.com"
features:
  basic_auth: false
  routes:
    school_direct_salaried: true
    school_direct_tuition_fee: true

environment:
  name: beta
