# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: build

on: 
  push:
     


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_HOSTNAME: localhost
      DOCKER_IMAGE: register-trainee-teacher-data
      DOCKER_REPO: ${{secrets.DOCKERHUB_USERNAME}}/register-trainee-teacher-data

    steps:
    - uses: actions/checkout@v2

    - name: Get values for current commit
      run: |
        GIT_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c 1-7)
        GIT_BRANCH="${GITHUB_REF##*/}"
        echo "::set-env name=GIT_SHA_SHORT::$GIT_SHA_SHORT"
        echo "::set-env name=GIT_BRANCH::$GIT_BRANCH"
        echo "::set-env name=SHA_TAG::$GIT_SHA_SHORT"
        echo "::set-env name=BRANCH_TAG::$GIT_BRANCH"

    - name: Login to docker hub
      run: echo "${{secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin

    - name: "docker pull ${{env.DOCKER_REPO}}:${{env.BRANCH_TAG}}"
      run: docker pull $DOCKER_REPO:$BRANCH_TAG || true

    - name: "docker-compose build"
      run:  docker-compose build

    - name: Bring images up
      run: |
        docker-compose up --no-build -d
        docker-compose exec -T web /bin/sh -c "./wait-for-command.sh -c 'nc -z db 5432' -s 0 -t 20"

    - name: Setup DB
      run: docker-compose exec -T web /bin/sh -c "bundle exec rails db:setup"

    - name: Run tests
      run: docker-compose exec -T web /bin/sh -c 'bundle exec rake'

    - name: Tag docker images
      run: docker tag ${{env.DOCKER_REPO}}:${{env.BRANCH_TAG}} ${{env.DOCKER_REPO}}:${{env.SHA_TAG}}
