name: 'Deploy to PaaS'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to eg: qa, staging, production etc'
        required: true
      sha:
        description: Commit sha to be deployed
        required: true

jobs:
  deploy:

    name: Deploy to PaaS
    env:
        DOCKER_REPO: dfedigital/register-trainee-teacher-data
        DOCKER_IMAGE: register-trainee-teacher-data

    if: ${{ !startsWith(github.event.inputs.environment, 'dfe-twd-rttd-pr') }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set Current Deployment Environment variable
        run: |
          echo $DOCKER_IMAGE

          case $DEPLOY_ENV in
            qa) next_env=staging ;;
            staging) next_env=production ;;
          esac

          echo "DOCKER_IMAGE=$DOCKER_IMAGE" >> $GITHUB_ENV
          echo "DEPLOY_ENV=$DEPLOY_ENV" >> $GITHUB_ENV
          echo "NEXT_ENV=$next_env" >> $GITHUB_ENV
        env:
          DOCKER_IMAGE: ${{env.DOCKER_REPO}}:${{ github.event.inputs.sha }}
          DEPLOY_ENV: ${{ github.event.inputs.environment }}


      - uses: softprops/turnstyle@v1
        name: Wait for other inprogress deployment runs
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_FOR_GITHUB_ACTION }}

      - name: Start ${{ github.event.inputs.environment }} Deployment
        uses: bobheadxi/deployments@v0.4.2
        id: deployment
        with:
          step: start
          token: ${{ secrets.API_TOKEN_FOR_GITHUB_ACTION }}
          env: ${{ github.event.inputs.environment }}
          ref: ${{ github.event.inputs.sha }}

      - name: Download app configuration file
        working-directory: terraform
        run: |
          echo $APP_SECRETS | base64 -d >> app_secrets.yml
        env:
          APP_SECRETS: ${{ secrets[format('APP_SECRETS_{0}', env.DEPLOY_ENV)] }}

      - name: Pin Terraform version
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: 0.13.5

      - name: Terraform init
        run: |
          terraform init -backend-config=terraform/workspace-variables/qa_backend.tfvars terraform
        env:
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_paas_app_docker_image: ${{env.DOCKER_REPO}}:${{ github.event.inputs.sha }}

      - name: Terraform Plan and Apply
        run: |
          terraform plan -var-file=terraform/workspace-variables/qa.tfvars terraform
          terraform apply -var-file=terraform/workspace-variables/qa.tfvars -auto-approve terraform
        env:
          TF_VAR_paas_app_docker_image: ${{env.DOCKER_REPO}}:${{ github.event.inputs.sha }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
          TF_VAR_paas_password: ${{ secrets.TF_VAR_PAAS_PASSWORD }}
          TF_VAR_paas_user: ${{ secrets.TF_VAR_PAAS_USER }}
          TF_VAR_paas_log_url: ${{ secrets.TF_VAR_PAAS_LOGGING_ENDPOINT_PORT }}
          TF_VAR_dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          TF_VAR_dockerhub_password: ${{ secrets.DOCKERHUB_PERSONAL_ACCESS_TOKEN }}

      - name: Update ${{ github.event.inputs.environment }} status
        if: ${{ always() }}
        uses: bobheadxi/deployments@v0.4.2
        with:
          step: finish
          token: ${{ secrets.API_TOKEN_FOR_GITHUB_ACTION }}
          env: ${{ github.event.inputs.environment }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          ref: ${{ github.event.inputs.sha }}
